/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ECKeyGeneratorFrame.java
 *
 * Created on 10.09.2008, 23:25:49
 */

package jcrypter.ecc;

import java.awt.EventQueue;
import java.io.BufferedOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.security.InvalidAlgorithmParameterException;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.SecureRandom;
import java.security.Security;
import java.security.spec.ECGenParameterSpec;
import java.util.Enumeration;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.bouncycastle.jce.ECNamedCurveTable;
import org.bouncycastle.jce.provider.BouncyCastleProvider;

/**
 *
 * @author uli
 */
public class ECKeyGeneratorFrame extends javax.swing.JFrame {

    /** Creates new form ECKeyGeneratorFrame */
    public ECKeyGeneratorFrame() {
        initComponents();
        //Register Bouncy castle provider
        Security.addProvider(new BouncyCastleProvider()); 
        //Populate the named curve selection combo box
        loadEcdsaCurves();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        standardButtonGroup = new javax.swing.ButtonGroup();
        curveComboBox = new javax.swing.JComboBox();
        curveLabel = new javax.swing.JLabel();
        ecgostRadioButton = new javax.swing.JRadioButton();
        ecdsaRadioButton = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        pubkeyFileLabel = new javax.swing.JLabel();
        privkeyFileLabel = new javax.swing.JLabel();
        pubFileField = new javax.swing.JTextField();
        privFileField = new javax.swing.JTextField();

        setTitle(i18n.getString("ECKeyGeneratorFrame.title")); // NOI18N

        curveLabel.setText(i18n.getString("ECKeyGeneratorFrame.curveLabel.text")); // NOI18N

        standardButtonGroup.add(ecgostRadioButton);
        ecgostRadioButton.setText(i18n.getString("ECKeyGeneratorFrame.ecgostRadioButton.text")); // NOI18N
        ecgostRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecgostRadioButtonActionPerformed(evt);
            }
        });

        standardButtonGroup.add(ecdsaRadioButton);
        ecdsaRadioButton.setSelected(true);
        ecdsaRadioButton.setText("ECDSA");
        ecdsaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecdsaRadioButtonActionPerformed(evt);
            }
        });

        okButton.setText(i18n.getString("ECKeyGeneratorFrame.okButton.text")); // NOI18N
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });

        pubkeyFileLabel.setText(i18n.getString("ECKeyGeneratorFrame.pubkeyFileLabel.text")); // NOI18N

        privkeyFileLabel.setText(i18n.getString("ECKeyGeneratorFrame.privkeyFileLabel.text")); // NOI18N

        pubFileField.setText("pub.ecp");
        pubFileField.setToolTipText(i18n.getString("ECKeyGeneratorFrame.pubFileField.toolTipText")); // NOI18N

        privFileField.setText("priv.ecs");
        privFileField.setToolTipText(i18n.getString("ECKeyGeneratorFrame.privFileField.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(privkeyFileLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(privFileField, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                    .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pubkeyFileLabel)
                            .addComponent(curveLabel))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pubFileField, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(curveComboBox, 0, 229, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ecdsaRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(ecgostRadioButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ecgostRadioButton)
                    .addComponent(ecdsaRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curveLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pubFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pubkeyFileLabel))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(privkeyFileLabel)
                    .addComponent(privFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ecdsaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecdsaRadioButtonActionPerformed
        EventQueue.invokeLater(new Runnable() {

                    @Override
                    public void run()
                        {
                            if(ecdsaRadioButton.isSelected()) {loadEcdsaCurves();}
                        }
                });
    }//GEN-LAST:event_ecdsaRadioButtonActionPerformed

    private void ecgostRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecgostRadioButtonActionPerformed
        EventQueue.invokeLater(new Runnable() {

                    @Override
                    public void run()
                        {
                            if(ecgostRadioButton.isSelected()) {loadEcgostCurves();}
                        }
                });
    }//GEN-LAST:event_ecgostRadioButtonActionPerformed

private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        {

            BufferedOutputStream pubOut = null;
            BufferedOutputStream privOut = null;
            try
            {
                ECGenParameterSpec ecGenSpec = new ECGenParameterSpec((String)curveComboBox.getSelectedItem());
                //TODO Make using ECGOST possible
                KeyPairGenerator g = null;
                if(ecgostRadioButton.isSelected()) {g = KeyPairGenerator.getInstance("ECGOST3410", "BC");}
                else {g = KeyPairGenerator.getInstance("ECDSA", "BC");}
                g.initialize(ecGenSpec, new SecureRandom());
                KeyPair pair = g.generateKeyPair();
                
                //TODO Encode in X509 or so, not in serializing
                pubOut = new BufferedOutputStream(new FileOutputStream(pubFileField.getText()));
                privOut = new BufferedOutputStream(new FileOutputStream(privFileField.getText()));
                
                pubOut.write(pair.getPublic().getEncoded());
                privOut.write(pair.getPrivate().getEncoded());
                
                pubOut.close();
                privOut.close();
            }
            catch (IOException ex)
            {
                Logger.getLogger(ECKeyGeneratorFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch (InvalidAlgorithmParameterException ex)
            {
                ex.printStackTrace();
            }
            catch (NoSuchAlgorithmException ex)
            {
                ex.printStackTrace();
            }
            catch (NoSuchProviderException ex)
            {
                ex.printStackTrace();
            }
            finally
            {
                try
                {
                    pubOut.close();
                    privOut.close();
                }
                catch (IOException ex)
                {
                    Logger.getLogger(ECKeyGeneratorFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }


}//GEN-LAST:event_okButtonMouseClicked

    private void loadEcdsaCurves()
    {
        curveComboBox.removeAllItems();
        Enumeration<String> curves = ECNamedCurveTable.getNames();
        while(curves.hasMoreElements())
        {
            curveComboBox.addItem(curves.nextElement());
        }
        curveComboBox.setSelectedItem("prime192v1");
    }

    private void loadEcgostCurves()
    {
        curveComboBox.removeAllItems();
        Enumeration<String> curves = ECNamedCurveTable.getNames();
        while(curves.hasMoreElements())
        {
            curveComboBox.addItem(curves.nextElement());
        }
        curveComboBox.setSelectedItem("GOSTR3410-2001-CryptoProA");
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ECKeyGeneratorFrame().setVisible(true);
            }
        });

    }

    //Resource bundle
    ResourceBundle i18n = ResourceBundle.getBundle("jcrypter/ecc/Bundle");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox curveComboBox;
    private javax.swing.JLabel curveLabel;
    private javax.swing.JRadioButton ecdsaRadioButton;
    private javax.swing.JRadioButton ecgostRadioButton;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField privFileField;
    private javax.swing.JLabel privkeyFileLabel;
    private javax.swing.JTextField pubFileField;
    private javax.swing.JLabel pubkeyFileLabel;
    private javax.swing.ButtonGroup standardButtonGroup;
    // End of variables declaration//GEN-END:variables

}
