/*
 * multiplicationTablesApplet.java
 *
 * Created on 4. April 2008, 12:45
 */

package multiplicationtables;

/**
 *
 * @author  User
 */
public class multiplicationTablesApplet extends java.applet.Applet {
    
    /** Initializes the applet multiplicationTablesApplet */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editingPanel = new java.awt.Panel();
        firstFactorField = new javax.swing.JTextField();
        multLabel = new java.awt.Label();
        secondFactorField = new javax.swing.JTextField();
        okPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        resultsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        firstFactorField.setColumns(2);
        firstFactorField.setFont(new java.awt.Font("Tahoma", 0, 36));
        firstFactorField.setToolTipText("Erster Faktor");
        editingPanel.add(firstFactorField);

        multLabel.setAlignment(java.awt.Label.CENTER);
        multLabel.setFont(new java.awt.Font("Dialog", 0, 36));
        multLabel.setText("x");
        editingPanel.add(multLabel);

        secondFactorField.setColumns(2);
        secondFactorField.setFont(new java.awt.Font("Tahoma", 0, 36));
        secondFactorField.setToolTipText("Erster Faktor");
        editingPanel.add(secondFactorField);

        add(editingPanel, java.awt.BorderLayout.NORTH);

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(47, 23));
        okButton.setMinimumSize(new java.awt.Dimension(47, 23));
        okPanel.add(okButton);

        add(okPanel, java.awt.BorderLayout.CENTER);

        jLabel1.setText("jLabel1");
        resultsPanel.add(jLabel1);

        add(resultsPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel editingPanel;
    private javax.swing.JTextField firstFactorField;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label multLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel okPanel;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JTextField secondFactorField;
    // End of variables declaration//GEN-END:variables
    
}
