/*
 * multiplicationTablesApplet.java
 *
 * Created on 4. April 2008, 12:45
 */

package multiplicationtables;

/**
 *
 * @author  User
 */
public class multiplicationTablesApplet extends java.applet.Applet {
    
    /** Initializes the applet multiplicationTablesApplet */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        mainPanel = new java.awt.Panel();
        okButton = new javax.swing.JButton();
        correctnessLabel = new javax.swing.JLabel();
        firstFactorLabel = new javax.swing.JLabel();
        secondFactorLabel = new javax.swing.JLabel();
        multLabel = new javax.swing.JLabel();
        isLabel = new javax.swing.JLabel();
        resultField = new javax.swing.JTextField();

        nameLabel.setText("Name:");

        setLayout(new java.awt.BorderLayout());

        okButton.setText("OK");

        correctnessLabel.setFont(new java.awt.Font("Tahoma", 1, 36));
        correctnessLabel.setForeground(new java.awt.Color(0, 255, 0));
        correctnessLabel.setText("RICHTIG!");

        firstFactorLabel.setFont(new java.awt.Font("Tahoma", 0, 48));
        firstFactorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstFactorLabel.setText("1");

        secondFactorLabel.setFont(new java.awt.Font("Tahoma", 0, 48));
        secondFactorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondFactorLabel.setText("2");

        multLabel.setFont(new java.awt.Font("Tahoma", 0, 48));
        multLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multLabel.setText("X");

        isLabel.setFont(new java.awt.Font("Tahoma", 0, 48));
        isLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isLabel.setText("=");

        resultField.setFont(new java.awt.Font("Tahoma", 0, 48));
        resultField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resultField.setText("5");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correctnessLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(firstFactorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(multLabel)
                                .addGap(3, 3, 3)
                                .addComponent(secondFactorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))
                        .addGap(30, 30, 30)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(secondFactorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multLabel)
                        .addComponent(isLabel)
                        .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(firstFactorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(correctnessLabel)
                .addGap(40, 40, 40))
        );

        add(mainPanel, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correctnessLabel;
    private javax.swing.JLabel firstFactorLabel;
    private javax.swing.JLabel isLabel;
    private java.awt.Panel mainPanel;
    private javax.swing.JLabel multLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField resultField;
    private javax.swing.JLabel secondFactorLabel;
    // End of variables declaration//GEN-END:variables
    
}
