/*
 * ResultsFrame.java
 *
 * Created on 23. Oktober 2008, 19:52
 */

package jcrypter.rand;

import java.util.ResourceBundle;

/**
 *
 * @author  uli
 */
public class ResultsFrame extends javax.swing.JFrame
{

    /** Creates new form ResultsFrame */
    public ResultsFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultsScrollPane = new javax.swing.JScrollPane();
        resultsField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(i18n.getString("ResultsFrame.title")); // NOI18N

        resultsField.setColumns(20);
        resultsField.setRows(5);
        resultsScrollPane.setViewportView(resultsField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void appendLine(String line)
    {
        resultsField.append(line + "\n");
    }
    
    public void append(String content)
    {
        resultsField.append(content);
    }
    
    private ResourceBundle i18n =
            ResourceBundle.getBundle("jcrypter/rand/Bundle");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea resultsField;
    private javax.swing.JScrollPane resultsScrollPane;
    // End of variables declaration//GEN-END:variables

}
